S01/activity/S01_Activity/S01_Activity/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('django_practice/', include('django_practice.urls')),
    path('admin/', admin.site.urls),
]

S01/activity/S01_Activity/django_practice/urls.py
from django.urls import path
from . import views

app_name = 'django_practice'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('groceryitem/<int:groceryitem_id>/', views.groceryitem, name="viewgroceryitem"),
    path('register', views.register, name="register"),
    path('change_password', views.change_password, name="change_password"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout")
]

S01/activity/S01_Activity/django_practice/models.py
from django.db import models

# Create your models here.
class GroceryItem(models.Model):
    item_name = models.CharField(max_length=50)
    category = models.CharField(max_length=50)
    status = models.CharField(max_length=50,default="pending")
    date_created = models.DateTimeField("date created")

S01/activity/S01_Activity/django_practice/forms.py
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(label="Username", max_length=20)
    first_name = forms.CharField(label="First Name", max_length=20)
    last_name = forms.CharField(label="Last Name", max_length=20)
    email = forms.CharField(label="Email", max_length=30)
    password1 = forms.CharField(label='Password', min_length=20)
    password2 = forms.CharField(label='Confirm password', min_length=8)

S01/activity/S01_Activity/django_practice/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict


from .models import GroceryItem
from .forms import RegisterForm


# Create your views here.
def index(request):
    groceryitem_list = GroceryItem.objects.all()
    context = { 
        'groceryitem_list' : groceryitem_list,
        'user' : request.user
        }
    return render(request, "django_practice/index.html", context)

def groceryitem(request, groceryitem_id):
    groceryitem = model_to_dict(GroceryItem.objects.get(pk=groceryitem_id))
    return render(request, "django_practice/groceryitem.html", groceryitem)

def register(request):

    context = {}

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid() == False:
            form = RegisterForm()

        else:
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

        user = authenticate(username=username, password=password)
        context = {
            "username" : username,
            "password" : password,
            "first_name" : first_name,
            "last_name" : last_name,
            "email" : email
        }

        if user is not None:
            register(request, user)
            return redirect("django_practice:index")
        
        else:
            context ={
                "error" : True
            }

    return render(request, "django_practice/register.html", context)



    # users = User.objects.all()
    # is_user_registered = False
    # context = {
    #     "is_user_registered" : is_user_registered
    # }

    # for indiv_user in users:
    #     if indiv_user.username == "russell17":
    #         is_user_registered = True
    #         break

    # if is_user_registered == False:
    #     user = User()
    #     user.username = "russell17"
    #     user.first_name = "Russell"
    #     user.last_name = "Divinagracia"
    #     user.email = "russ@mail.com"
    #     user.set_password("russ1122")
    #     user.is_staff = False
    #     user.is_active = True
    #     user.save()
    #     context = {
    #         "first_name" : user.first_name,
    #         "last_name" : user.last_name
    #     }
    # return render(request, "django_practice/register.html", context)

def change_password(request):
    is_user_authenticated = False

    user = authenticate(username="russell17", password="russ1122")
    print(user)

    if user is not None:
        authenticated_user = User.objects.get(username="russell17")
        authenticated_user.set_password("russ217")
        authenticated_user.save()
        is_user_authenticated = True

    context = {
        "is_user_authenticated" : is_user_authenticated
    }
    return render(request, "django_practice/change_password.html", context) 

def login_view(request):
    username = "russell17"
    password = "russ217"
    user = authenticate(username=username, password=password)
    context = {
        "is_user_authenticated" : False
    }
    print(user)
    if user is not None:
        login(request, user)
        return redirect("django_practice:index")
    else:
        return render(request, "django_practice/login.html", context)
    
def logout_view(request):
    logout(request)
    return redirect("django_practice:index")

S01/activity/S01_Activity/django_practice/templates/django_practice/change_password.html
{% if is_user_authenticated == False %}

    <h1>Invalid User Credentials!</h1>
    <p>Check if the username and password are correct</p>

{% else %}
    <h1>User Password Successlly Updated!</h1>
    <p>The password has been successlly updated</p>

{% endif %}

S01/activity/S01_Activity/django_practice/templates/django_practice/groceryitem.html
<h1>{{ item_name }}</h1>
<h3>Category</h3>
<p>{{ category }}</p>
<h3>Status</h3>
<p>{{ status }}</p>
<a href="index">Back to index page</a>

S01/activity/S01_Activity/django_practice/templates/django_practice/index.html
{% extends 'base.html' %}

{% block  tittle %}Home{% endblock %}

{% block content %} 

{% if groceryitem_list and user.is_anonymous == False %}

    <h1>Welcome {{user.first_name}} {{user.last_name}}!</h1> 
    <ul>
        {% for groceryitem in groceryitem_list %}
        <li>
            <a href="groceryitem/{{groceryitem.id}}/">{{groceryitem.item_name}}</a>
        </li>
        {% endfor %}
    </ul>
    
{% elif groceryitem_list.count == 0 and user %}

    <p>No grocery items have been added.</p>

{% else %}

    <h1>You are not authorized to access this page.</h1>
    <p>Kindly login <a href="login">here</a></p>
    
{% endif %}
{% endblock %}

S01/activity/S01_Activity/django_practice/templates/django_practice/login.html
{% if is_user_authenticated == False %}

    <h1>Something Went Wrong</h1>
    <p> Please contact your administrator or reset your password</p>

{% endif %}

S01/activity/S01_Activity/django_practice/templates/django_practice/register.html
{% extends 'base.html' %}

{% block  tittle %}Register{% endblock %}

{% block content %} 

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center my-3">Register</h1>
            
            <form action="{% url 'django_practice:register' %}" method="post">

                {% csrf_token %}
                
                <div class="mb-3">
                    <label for="username" class="form-label">Username:</label>
                    <input type="text" class="form-control" id="username" name="username" value="{{username}}" maxlength="20" required>
                </div>
                <div class="mb-3">
                    <label for="first_name" class="form-label">First Name:</label>
                    <input type="text" class="form-control" id="first_name" name="first_name" value="{{first_name}}" maxlength="20" required>
                </div>
                <div class="mb-3">
                    <label for="last_name" class="form-label">Last Name:</label>
                    <input type="text" class="form-control" id="last_name" name="last_name" value="{{last_name}}" maxlength="20" required>
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email:</label>
                    <input type="text" class="form-control" id="email" name="email" value="{{email}}" maxlength="30" required>
                </div>
                <div class="mb-3">
                    <label for="password1" class="form-label">Password:</label>
                    <input type="password" class="form-control" id="password1" name="password1" value="{{password1}}" maxlength="20" required>
                </div>
                <div class="mb-3">
                    <label for="password2" class="form-label">Confirm Password:</label>
                    <input type="password" class="form-control" id="password2" name="password2" value="{{password2}}" maxlength="20" required>
                </div>
                <div>
                    <input class="btn btn-success" type="submit" value="Login">
                </div>
            </form>

        </div>
    </div>
</div>

{% endblock%}









<!-- {% if is_user_registered == False %}
    <h1> Duplicate User Found! </h1>
    <p> A duplicate user has been found, user creation unsuccessful</p>

{% else %}

    <h1>User Successlly Created</h1>
    <p>the account for {{first_name}} {{last_name}} has been successlly created</p>

{% endif %} -->

S01/activity/S01_Activity/templates/base.html
<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block tittle %} Django_Practice App {% endblock%}</title>

        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    </head>

    <body>
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}

        <!-- Bootstrap Script -->
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
        
    </body>

</html>

S01/activity/S01_Activity/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Django_Practice</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'django_practice:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'django_practice:register' %}">Regsiter</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'django_practice:login' %}">Log in</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'django_practice:logout' %}">Log out</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>